### ISSUE TITLE
Type declaration path is broken

### ISSUE THREAD

**Issue by neet** [kgurkan/rxjs-async-iterator#3]
Currently `typing` property in package.json is `./dist/types/index.d.ts` but this file seems to not exist. The correct path is `./dist/index.d.ts`

![image](https://user-images.githubusercontent.com/19276905/80866218-799e8080-8cc8-11ea-9f6c-a20b9b282eee.png)

<details>
<summary>error details</summary>

```
Could not find a declaration file for module 'rxjs-async-iterator'. '/Users/nucx/.ghq/github.com/visible/visible/node_modules/rxjs-async-iterator/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/rxjs-async-iterator` if it exists or add a new declaration (.d.ts) file containing `declare module 'rxjs-async-iterator';`ts(7016)
```
</details>

**Comment by dimaqq** [comment]
👏
